import { useState } from 'react';
import { Heart, Pill, Calendar, Phone, BookOpen, CheckCircle2, Loader2, FileHeart, ExternalLink, Youtube, AlertCircle, Mail, Check } from 'lucide-react';
import type { SOAPNote, SessionStatus, Patient } from '../types';
import jsPDF from 'jspdf';

interface PatientSummaryPanelProps {
  note: SOAPNote | null;
  patient?: Patient;
  status: SessionStatus;
}

function ShimmerBlock({ height = 'h-4', width = 'w-full' }: { height?: string; width?: string }) {
  return <div className={`${height} ${width} rounded shimmer`} />;
}

function buildYouTubeUrl(query: string) {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
}

function buildMedlinePlusUrl(query: string) {
  return `https://medlineplus.gov/search/?query=${encodeURIComponent(query)}`;
}

const STATIC_LABELS = {
  pageTitle: 'Visit Summary',
  sections: [
    'What We Discussed Today',
    'What the Doctor Found',
    'Your Care Instructions',
    'Your Treatment Plan',
    'Follow-Up Appointment',
    'When to Seek Urgent Help',
  ],
  footer: 'Generated by ClinicalEar',
};

const SUMMARY_SECTIONS = [
  {
    label: 'What We Discussed Today',
    getValue: (n: SOAPNote) => n.subjective || "See your doctor's notes for details.",
  },
  {
    label: 'What the Doctor Found',
    getValue: (n: SOAPNote) => n.assessment || 'Your doctor will discuss findings with you.',
  },
  {
    label: 'Your Care Instructions',
    getValue: (n: SOAPNote) =>
      n.patient_instructions?.length
        ? n.patient_instructions.map((instr, i) => `${i + 1}. ${instr}`).join('\n')
        : n.plan || 'Follow the instructions provided by your care team.',
  },
  {
    label: 'Follow-Up Appointment',
    getValue: () =>
      'Please attend your scheduled follow-up appointment. Contact your care team if you have questions or concerns before then.',
  },
  {
    label: 'When to Seek Urgent Help',
    getValue: () =>
      'Go to the emergency room or call 911 if your symptoms suddenly worsen, you have difficulty breathing, chest pain, or feel faint.',
  },
];

export default function PatientSummaryPanel({ note, patient, status }: PatientSummaryPanelProps) {
  const instructions = note?.patient_instructions ?? [];
  const resourceQueries = note?.resource_queries ?? [];
  const [emailed, setIsEmailed] = useState(false);
  const email = "wacotoc291@niprack.com";

  const translateField = async (text: string): Promise<string> => {
    if (!patient?.preferred_language) return text;
    const resp = await fetch('http://localhost:8000/api/translate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text, target_lang: patient.preferred_language }),
    });
    const data = await resp.json();
    return data.translated;
  };

const renderPage = (
  doc: jsPDF,
  fields: { label: string; content: string }[],
  isTranslated: boolean,
  pageTitle: string = 'Visit Summary'
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

// ── Page background ──
doc.setFillColor(248, 249, 252); // soft off-white
doc.rect(0, 0, pageWidth, pageHeight, 'F');

// ── Top accent line ──
doc.setFillColor(99, 102, 241); // indigo
doc.rect(0, 0, pageWidth, 3, 'F');

// ── Welcome banner ──
doc.setFillColor(245, 243, 255); // very light purple
doc.roundedRect(14, 10, pageWidth - 28, 28, 3, 3, 'F');
doc.setDrawColor(196, 181, 253);
doc.setLineWidth(0.3);
doc.roundedRect(14, 10, pageWidth - 28, 28, 3, 3, 'S');

  // ── Title ──
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(249, 168, 212); // #F9A8D4
  doc.text(pageTitle.toUpperCase(), 22, 21);

  // ── Subtitle ──
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(122, 154, 184); // #7A9AB8
  const subtitle = isTranslated
    ? `Translated to ${patient?.preferred_language ?? ''} · Generated on ${new Date().toLocaleDateString()}`
    : `Original (English) · Generated on ${new Date().toLocaleDateString()}`;
  doc.text(subtitle, 22, 30);

  // ── Section colors matching UI ──
const sectionStyles: Record<string, { r: number; g: number; b: number; labelR: number; labelG: number; labelB: number; bgR: number; bgG: number; bgB: number }> = {
  'What We Discussed Today':  { r: 37,  g: 99,  b: 235, labelR: 29,  labelG: 78,  labelB: 216, bgR: 239, bgG: 246, bgB: 255 },
  'What the Doctor Found':    { r: 5,   g: 150, b: 105, labelR: 4,   labelG: 120, labelB: 87,  bgR: 236, bgG: 253, bgB: 245 },
  'Your Care Instructions':   { r: 217, g: 119, b: 6,   labelR: 180, labelG: 83,  labelB: 9,   bgR: 255, bgG: 251, bgB: 235 },
  'Your Treatment Plan':      { r: 217, g: 119, b: 6,   labelR: 180, labelG: 83,  labelB: 9,   bgR: 255, bgG: 251, bgB: 235 },
  'Follow-Up Appointment':    { r: 109, g: 40,  b: 217, labelR: 91,  labelG: 33,  labelB: 182, bgR: 245, bgG: 243, bgB: 255 },
  'When to Seek Urgent Help': { r: 220, g: 38,  b: 38,  labelR: 185, labelG: 28,  labelB: 28,  bgR: 254, bgG: 242, bgB: 242 },
};

  let y = 48;

  fields.forEach(({ label, content }) => {
    const style = sectionStyles[label] ?? { r: 29, g: 78, b: 216, labelR: 147, labelG: 187, labelB: 255 };
    const { r, g, b, labelR, labelG, labelB } = style;

    // Estimate content height
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const split = doc.splitTextToSize(content || 'N/A', pageWidth - 44);
    const contentHeight = split.length * 6 + 10;
    const cardHeight = 18 + contentHeight;

    // Page break check
    if (y + cardHeight > pageHeight - 20) {
      doc.addPage();
      doc.setFillColor(7, 13, 28);
      doc.rect(0, 0, pageWidth, pageHeight, 'F');
      y = 20;
    }

    // ── Card background ──
    doc.setFillColor(10, 22, 40); // #0A1628
    doc.roundedRect(14, y, pageWidth - 28, cardHeight, 3, 3, 'F');

    // ── Left accent border ──
    doc.setFillColor(r, g, b);
    doc.rect(14, y, 3, cardHeight, 'F');

    // ── Header bar ──
    doc.setFillColor(r, g, b, 0.08);
    doc.setFillColor(
      Math.min(255, r + Math.round((255 - r) * 0.92)),
      Math.min(255, g + Math.round((255 - g) * 0.92)),
      Math.min(255, b + Math.round((255 - b) * 0.92))
    );
    // Use a very subtle tinted header — manually mix with dark bg
    doc.setFillColor(
      Math.round(10 + r * 0.08),
      Math.round(22 + g * 0.08),
      Math.round(40 + b * 0.08)
    );
    doc.rect(17, y, pageWidth - 31, 10, 'F');

    // ── Section label ──
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(labelR, labelG, labelB);
    doc.text(label.toUpperCase(), 22, y + 7);

    // ── Divider ──
    doc.setDrawColor(r, g, b);
    doc.setLineWidth(0.3);
    doc.line(17, y + 10, pageWidth - 14, y + 10);

    // ── Content ──
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(122, 154, 184); // #7A9AB8 — matches serif body color in UI
    doc.setCharSpace(0);
    doc.text(split, 22, y + 17);

    y += cardHeight + 5;
  });

// ── Footer ──
doc.setFillColor(248, 249, 252);
doc.rect(0, pageHeight - 12, pageWidth, 12, 'F');
doc.setDrawColor(229, 231, 235);
doc.setLineWidth(0.3);
doc.line(14, pageHeight - 12, pageWidth - 14, pageHeight - 12);
doc.setFontSize(7);
doc.setTextColor(107, 114, 128); // #6B7280
doc.text('Generated by ClinicalEar', 14, pageHeight - 4);
doc.text(new Date().toLocaleDateString(), pageWidth - 14, pageHeight - 4, { align: 'right' });
};

const generatePDF = async (output: 'preview' | 'base64' = 'preview') => {
  if (!note) return '';
  const doc = new jsPDF();

  const summaryFields = SUMMARY_SECTIONS.map(({ label, getValue }) => ({
    label,
    content: getValue(note),
  }));

  if (patient?.preferred_language) {
    // Translate both labels AND content
    const [translatedFields, translatedTitle] = await Promise.all([
      Promise.all(
        summaryFields.map(async ({ label, content }) => ({
          label: await translateField(label),
          content: await translateField(content),
        }))
      ),
      translateField(STATIC_LABELS.pageTitle),
    ]);

    renderPage(doc, translatedFields, true, translatedTitle);
    doc.addPage();
  }

  renderPage(doc, summaryFields, false, STATIC_LABELS.pageTitle);

  if (output === 'preview') {
    window.open(doc.output('bloburl'), '_blank');
    return '';
  }
  return doc.output('datauristring');
};

  const handleEmail = async () => {
    if (!note || !email) return;
    setIsEmailed(true);
    const pdfBase64 = await generatePDF('base64') as string;
    const base64Content = pdfBase64.replace(/^data:.+;base64,/, '');
    await fetch('http://localhost:8000/api/send-appointment-summary', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        patient_email: email,
        pdf_base64: base64Content,
      }),
    });
  };

  return (
    <div className="flex flex-col h-full tab-panel-enter" style={{ background: '#070D1C' }}>
      <div className="flex-1 overflow-y-auto px-4 py-4 space-y-3">

        {!note && status === 'idle' && (
          <div className="flex flex-col items-center justify-center h-full gap-5 py-24 text-center">
            <div className="w-14 h-14 rounded-xl flex items-center justify-center"
              style={{ background: 'rgba(244,114,182,0.07)', border: '1px solid rgba(244,114,182,0.15)' }}>
              <FileHeart className="w-6 h-6" style={{ color: 'rgba(244,114,182,0.35)' }} />
            </div>
            <div>
              <p className="text-sm font-semibold" style={{ color: '#2E4A66' }}>No summary yet</p>
              <p className="text-xs mt-1" style={{ color: '#1A2E44' }}>A patient-friendly summary will appear after the consultation</p>
            </div>
          </div>
        )}

        {!note && status === 'recording' && (
          <div className="flex flex-col items-center justify-center h-full gap-5 py-24 text-center">
            <div className="w-14 h-14 rounded-xl flex items-center justify-center"
              style={{ background: 'rgba(244,114,182,0.05)', border: '1px solid rgba(244,114,182,0.12)' }}>
              <FileHeart className="w-6 h-6" style={{ color: 'rgba(244,114,182,0.3)' }} />
            </div>
            <p className="text-sm" style={{ color: '#2E4A66' }}>Summary will appear after the consultation ends</p>
          </div>
        )}

        {!note && status === 'processing' && (
          <div className="space-y-3 pt-1">
            <div className="flex items-center gap-2 mb-4">
              <Loader2 className="w-4 h-4 animate-spin" style={{ color: '#F472B6' }} />
              <span className="text-sm font-medium" style={{ color: '#4A7FA8' }}>Preparing patient summary…</span>
            </div>
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="rounded-xl overflow-hidden" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
                <div className="px-4 py-2.5 flex items-center gap-3" style={{ background: 'rgba(244,114,182,0.05)' }}>
                  <div className="w-6 h-6 rounded shrink-0 shimmer" />
                  <ShimmerBlock height="h-3" width="w-32" />
                </div>
                <div className="px-4 py-3 space-y-2" style={{ background: '#0A1628' }}>
                  <ShimmerBlock height="h-3" />
                  <ShimmerBlock height="h-3" />
                  <ShimmerBlock height="h-3" width="w-3/4" />
                </div>
              </div>
            ))}
          </div>
        )}

        {note && (
          <>
            {/* Welcome banner with email button */}
            <div className="rounded-xl p-4 note-section"
              style={{ background: 'rgba(244,114,182,0.07)', border: '1px solid rgba(244,114,182,0.15)' }}>
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4" style={{ color: '#F472B6' }} />
                  <span className="text-[10px] font-black uppercase tracking-widest" style={{ color: '#F9A8D4' }}>
                    Your Visit Summary
                  </span>
                </div>
                <button
                  onClick={handleEmail}
                  disabled={emailed}
                  className="flex items-center gap-1.5 text-[10px] font-semibold px-3 py-1 rounded tracking-wide"
                  style={
                    emailed
                      ? { background: 'rgba(16,185,129,0.12)', color: '#6EE7B7', border: '1px solid rgba(16,185,129,0.2)', opacity: 0.6, cursor: 'not-allowed' }
                      : { background: 'rgba(29,78,216,0.2)', color: '#93BBFF', border: '1px solid rgba(29,78,216,0.35)' }
                  }
                >
                  {emailed ? <Check className="w-3.5 h-3.5" /> : <Mail className="w-3.5 h-3.5" />}
                  {emailed ? 'Emailed!' : 'Email Summary'}
                </button>
              </div>
              <p style={{ fontFamily: 'Lora, Georgia, serif', fontSize: '13px', lineHeight: '1.75', color: '#7A9AB8' }}>
                Thank you for your visit today. Below is a plain-language summary of what was
                discussed, along with your care instructions. Please keep this for your records.
              </p>
            </div>

            <SummaryCard icon={<BookOpen className="w-4 h-4" />} title="What We Discussed Today"
              accentColor="#93BBFF" bgColor="rgba(29,78,216,0.08)" borderColor="rgba(29,78,216,0.2)">
              <p style={{ fontFamily: 'Lora, Georgia, serif', fontSize: '13.5px', lineHeight: '1.8', color: '#7A9AB8' }}>
                {note.subjective || "See your doctor's notes for details."}
              </p>
            </SummaryCard>

            <SummaryCard icon={<Heart className="w-4 h-4" />} title="What the Doctor Found"
              accentColor="#6EE7B7" bgColor="rgba(16,185,129,0.08)" borderColor="rgba(16,185,129,0.2)">
              <p style={{ fontFamily: 'Lora, Georgia, serif', fontSize: '13.5px', lineHeight: '1.8', color: '#7A9AB8' }}>
                {note.assessment || 'Your doctor will discuss findings with you.'}
              </p>
            </SummaryCard>

            {instructions.length > 0 && (
              <SummaryCard icon={<Pill className="w-4 h-4" />} title="Your Care Instructions"
                badge="Follow These Steps" accentColor="#FCD34D"
                bgColor="rgba(217,119,6,0.08)" borderColor="rgba(217,119,6,0.22)">
                <ul className="space-y-2.5 mt-1">
                  {instructions.map((instr, i) => (
                    <li key={i} className="flex items-start gap-3">
                      <span className="shrink-0 w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-black mt-0.5"
                        style={{ background: 'rgba(217,119,6,0.18)', color: '#FCD34D', fontFamily: 'JetBrains Mono, monospace' }}>
                        {i + 1}
                      </span>
                      <span style={{ fontFamily: 'Lora, Georgia, serif', fontSize: '13px', lineHeight: '1.7', color: '#7A9AB8' }}>
                        {instr}
                      </span>
                    </li>
                  ))}
                </ul>
              </SummaryCard>
            )}

            {instructions.length === 0 && (
              <SummaryCard icon={<Pill className="w-4 h-4" />} title="Your Treatment Plan"
                accentColor="#FCD34D" bgColor="rgba(217,119,6,0.08)" borderColor="rgba(217,119,6,0.2)">
                <p style={{ fontFamily: 'Lora, Georgia, serif', fontSize: '13.5px', lineHeight: '1.8', color: '#7A9AB8' }}>
                  {note.plan || 'Follow the instructions provided by your care team.'}
                </p>
              </SummaryCard>
            )}

            <SummaryCard icon={<Calendar className="w-4 h-4" />} title="Follow-Up Appointment"
              accentColor="#C4B5FD" bgColor="rgba(139,92,246,0.08)" borderColor="rgba(139,92,246,0.2)">
              <p style={{ fontFamily: 'Lora, Georgia, serif', fontSize: '13.5px', lineHeight: '1.8', color: '#7A9AB8' }}>
                Please attend your scheduled follow-up appointment. Contact your care team if you have questions or concerns before then.
              </p>
            </SummaryCard>

            <SummaryCard icon={<AlertCircle className="w-4 h-4" />} title="When to Seek Urgent Help"
              accentColor="#FCA5A5" bgColor="rgba(239,68,68,0.06)" borderColor="rgba(239,68,68,0.18)">
              <p style={{ fontFamily: 'Lora, Georgia, serif', fontSize: '13.5px', lineHeight: '1.8', color: '#7A9AB8' }}>
                Go to the emergency room or call 911 if your symptoms suddenly worsen, you have difficulty breathing, chest pain, or feel faint.
              </p>
            </SummaryCard>

            {resourceQueries.length > 0 && (
              <div className="rounded-xl overflow-hidden note-section" style={{ border: '1px solid rgba(255,255,255,0.08)' }}>
                <div className="flex items-center gap-2.5 px-4 py-3"
                  style={{ background: 'rgba(255,255,255,0.03)', borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
                  <Youtube className="w-4 h-4" style={{ color: '#FF4444' }} />
                  <span className="text-xs font-bold uppercase tracking-widest" style={{ color: '#94A3B8' }}>Learn More</span>
                  <span className="text-[10px]" style={{ color: '#1E3A5A' }}>— helpful videos &amp; resources</span>
                </div>
                <div className="px-4 py-3 space-y-2.5" style={{ background: '#0A1628' }}>
                  {resourceQueries.map((query, i) => (
                    <div key={i} className="flex items-center gap-2.5">
                      <a href={buildYouTubeUrl(query)} target="_blank" rel="noopener noreferrer"
                        className="flex items-center gap-2 px-3 py-2 rounded-lg flex-1 transition-all duration-150 hover:opacity-90"
                        style={{ background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.18)' }}>
                        <Youtube className="w-3.5 h-3.5 shrink-0" style={{ color: '#FF4444' }} />
                        <span className="text-xs flex-1 truncate" style={{ color: '#94A3B8' }}>{query}</span>
                        <ExternalLink className="w-3 h-3 shrink-0" style={{ color: '#4A3030' }} />
                      </a>
                      <a href={buildMedlinePlusUrl(query)} target="_blank" rel="noopener noreferrer"
                        className="flex items-center gap-1.5 px-2.5 py-2 rounded-lg transition-all duration-150 hover:opacity-90 shrink-0"
                        style={{ background: 'rgba(29,78,216,0.1)', border: '1px solid rgba(29,78,216,0.22)' }}>
                        <Phone className="w-3.5 h-3.5" style={{ color: '#60A5FA' }} />
                        <span className="text-[10px] font-semibold" style={{ color: '#60A5FA' }}>MedlinePlus</span>
                        <ExternalLink className="w-3 h-3" style={{ color: '#1E3A5A' }} />
                      </a>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {note.icd10_suggestions.length > 0 && (
              <div className="rounded-xl overflow-hidden note-section" style={{ border: '1px solid rgba(255,255,255,0.07)' }}>
                <div className="flex items-center gap-2.5 px-4 py-3"
                  style={{ background: 'rgba(255,255,255,0.03)', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                  <span className="text-[9px] font-black px-1.5 py-0.5 rounded"
                    style={{ background: 'rgba(255,255,255,0.07)', color: '#3D5878', fontFamily: 'JetBrains Mono, monospace' }}>Dx</span>
                  <span className="text-xs font-semibold" style={{ color: '#4A6A88' }}>Diagnosis Codes</span>
                </div>
                <div className="px-4 py-3 flex flex-wrap gap-2" style={{ background: '#0A1628' }}>
                  {note.icd10_suggestions.map((code, i) => (
                    <span key={i} className="mono-chip px-2.5 py-1 text-xs rounded-lg font-medium"
                      style={{ background: 'rgba(255,255,255,0.05)', color: '#4A6A88', border: '1px solid rgba(255,255,255,0.09)' }}>
                      {code}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}

interface SummaryCardProps {
  icon: React.ReactNode;
  title: string;
  badge?: string;
  accentColor: string;
  bgColor: string;
  borderColor: string;
  children: React.ReactNode;
}

function SummaryCard({ icon, title, badge, accentColor, bgColor, borderColor, children }: SummaryCardProps) {
  return (
    <div className="rounded-xl overflow-hidden note-section" style={{ border: `1px solid ${borderColor}` }}>
      <div className="flex items-center justify-between px-4 py-2.5"
        style={{ background: bgColor, borderBottom: `1px solid ${borderColor}` }}>
        <div className="flex items-center gap-2">
          <span style={{ color: accentColor }}>{icon}</span>
          <span className="text-xs font-bold" style={{ color: accentColor }}>{title}</span>
        </div>
        {badge && (
          <span className="text-[9px] font-black uppercase tracking-widest px-2 py-0.5 rounded"
            style={{ background: `${accentColor}18`, color: accentColor, border: `1px solid ${accentColor}30` }}>
            {badge}
          </span>
        )}
      </div>
      <div className="px-4 py-3.5" style={{ background: '#0A1628' }}>
        {children}
      </div>
    </div>
  );
}